# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5874f5f6f15d290aca5c6615fc1fbea67fafa590281ece3db47a9c8feb56404f93ed8caca23700b6f44bf7b927294f4858c0d962cfc0334807dc447dfa14d0ff

test:
  secret_key_base: fa52f520b12a8e721af4b8898633f7455ec8695a11944db4ab93a0608f99a96fe22c14d8eefd00e4b793306d41e3fe90be1f20e3c6ff24fc2c8b6de3b2ebebdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
